import { Component, FileText, Monitor, RefreshCcw, Rocket } from "lucide-react";

export const navigations: INavigation[] = [
  { name: "About me", href: "#about", icon: Rocket },
  { name: "Techstack", href: "#skills", icon: Component },
  { name: "Projects", href: "#projects", icon: Monitor },
  { name: "Experiences", href: "#experiences", icon: RefreshCcw },
  { name: "Contact", href: "#contact", icon: FileText },
];

export const stats: IStat[] = [
  { label: "Years Experience", value: 4, suffix: "+" },
  { label: "Projects Shipped", value: 9, suffix: "+" },
  { label: "Technologies", value: 22, suffix: "+" },
];

export const techStack: ITech[] = [
  { imageUri: "/next-js.png", name: "Next JS", category: "frontend" },
  {
    imageUri: "/react-js.png",
    name: "React JS & React Native",
    category: "frontend",
  },
  { imageUri: "/tailwind-css.png", name: "Tailwind", category: "frontend" },
  { imageUri: "/shadcn-ui.png", name: "Shadcn UI", category: "frontend" },
  { imageUri: "/mantine.png", name: "Mantine UI", category: "frontend" },
  { imageUri: "/ant-design.svg", name: "Ant Design", category: "frontend" },
  { imageUri: "/mui.png", name: "Material UI", category: "frontend" },
  {
    imageUri: "/tanstack.png",
    name: "Tanstack Ecosystem",
    category: "frontend",
  },
  { imageUri: "/redux.png", name: "Redux Ecosystem", category: "frontend" },
  { imageUri: "/zustand.jpg", name: "Zustand", category: "frontend" },
  { imageUri: "/node-js.png", name: "Node JS", category: "backend" },
  { imageUri: "/nest-js.png", name: "Nest JS", category: "backend" },
  { imageUri: "/express-js.png", name: "Express JS", category: "backend" },
  { imageUri: "/mongo-db.png", name: "MongoDB", category: "backend" },
  { imageUri: "/postgresql.png", name: "PostgreSQL", category: "backend" },
  { imageUri: "/redis.svg", name: "Redis", category: "backend" },
  { imageUri: "/rabbitmq.svg", name: "RabbitMQ", category: "backend" },
  { imageUri: "/prisma.png", name: "Prisma", category: "backend" },
  { imageUri: "/socket.png", name: "Socket.io", category: "backend" },
  { imageUri: "/docker.png", name: "Docker", category: "tools" },
  { imageUri: "/web-rtc.png", name: "WebRTC", category: "tools" },
  // { imageUri: "/metamask.png", name: "MetaMask", category: "tools" },
  // { imageUri: "/phantom.jpg", name: "Phantom", category: "tools" },
  // { imageUri: "/ton.jpg", name: "Ton", category: "tools" },
  { imageUri: "/ubuntu.png", name: "Ubuntu", category: "tools" },
  { imageUri: "/aws-s3.png", name: "Amazon S3", category: "tools" },
  { imageUri: "/aws-ec2.png", name: "Amazon EC2", category: "tools" },
  { imageUri: "/aws-kms.png", name: "Amazon KMS", category: "tools" },
  { imageUri: "/firebase.png", name: "Firebase", category: "tools" },
  { imageUri: "/claude.svg", name: "Claude", category: "tools" },
];

export const listProject: IProject[] = [
  {
    name: "DreamFly",
    role: "Frontend Developer",
    summary:
      "A travel lottery platform featuring user and admin applications where users can purchase tickets for a chance to win international travel experiences through randomized prize selection systems.",
    responsibilities: [
      "Developed and maintained both customer-facing and admin CMS applications.",
      "Built responsive and visually engaging user interfaces focused on conversion and user engagement.",
      "Implemented authentication systems supporting email/password, Google, and Facebook login flows.",
      "Integrated ticket purchasing workflows, account management, and prize participation systems.",
      "Developed admin dashboard interfaces for managing users, campaigns, tickets, and winner selection operations.",
      "Optimized SEO structure and frontend performance for improved discoverability and user experience.",
      "Collaborated closely with backend services to support real-time campaign and ticket management.",
      "Participated in Docker-based deployment and environment configuration workflows.",
    ],
    technicalHighlights: [
      "Modern travel booking UI/UX",
      "SEO-focused frontend architecture",
      "Social authentication integration",
      "Interactive ticket purchasing flows",
      "Admin CMS dashboard system",
      "Responsive and conversion-focused design",
      "Performance-optimized frontend",
      "Docker-based deployment workflow",
      "State management with Zustand & TanStack Query",
    ],
    previewImages: [
      "/project-images/dream-fly/1.png",
      "/project-images/dream-fly/2.png",
      "/project-images/dream-fly/3.png",
      "/project-images/dream-fly/4.png",
      "/project-images/dream-fly/5.png",
      "/project-images/dream-fly/6.png",
      "/project-images/dream-fly/7.png",
      "/project-images/dream-fly/8.png",
      "/project-images/dream-fly/9.png",
    ],
    logo: "/project-images/dream-fly/logo.svg",
  },
  {
    name: "Regent Reserve",
    role: "Frontend Developer",
    summary:
      "A premium booking platform ecosystem including customer-facing landing pages and CMS systems for hotel and flight reservations, membership management, vouchers, and account operations.",
    responsibilities: [
      "Developed and maintained both booking platform interfaces and admin CMS systems using NextJS.",
      "Built complex flight search and booking interfaces integrated with third-party provider APIs.",
      "Handled large-scale and highly dynamic flight data with complex business logic processing to ensure accurate pricing, schedules, and booking information.",
      "Optimized rendering performance for heavy datasets and real-time UI updates using React 19 features such as useTransition and memoization strategies.",
      "Implemented smooth and responsive user experiences for booking flows, filtering systems, and account management.",
      "Integrated membership systems, voucher workflows, and account-related functionalities.",
      "Collaborated closely with backend and third-party service providers to ensure reliable booking operations.",
    ],
    technicalHighlights: [
      "Complex flight booking workflows",
      "Large-scale data processing",
      "High-performance rendering optimization",
      "React 19 performance strategies",
      "Third-party API integration",
      "Modern booking dashboard UI",
      "Responsive and smooth UX",
      "State management with Zustand & TanStack Query",
    ],
    previewImages: [
      "/project-images/regent-reserve/7.png",
      "/project-images/regent-reserve/8.png",
      "/project-images/regent-reserve/9.png",
      "/project-images/regent-reserve/1.png",
      "/project-images/regent-reserve/2.png",
      "/project-images/regent-reserve/3.png",
      "/project-images/regent-reserve/4.png",
      "/project-images/regent-reserve/5.png",
      "/project-images/regent-reserve/6.png",
    ],
    logo: "/project-images/regent-reserve/logo.png",
  },
  {
    name: "Interra",
    role: "Frontend Developer",
    summary:
      "A modern multi-chain trading platform inspired by advanced crypto trading terminals, enabling users to trade assets across Solana, BNB Chain, Ethereum, Arbitrum, and other EVM-compatible ecosystems through system-managed wallet infrastructure.",
    responsibilities: [
      "Developed and optimized the frontend trading application using ReactJS.",
      "Integrated backend APIs for token trading, wallet interactions, market data, and portfolio management.",
      "Built high-performance real-time interfaces handling large-scale socket data streams and frequent UI updates.",
      "Optimized rendering performance for large datasets including token tables, transaction histories, and live trading activities.",
      "Implemented wallet connection flows for Solana and EVM-compatible chains.",
      "Collaborated closely with backend and blockchain services to support seamless multi-chain trading experiences.",
      "Designed and maintained responsive, modern, and trading-focused UI/UX experiences.",
    ],
    technicalHighlights: [
      "Real-time socket-based trading updates",
      "High-performance rendering optimization",
      "Large-scale data virtualization with TanStack Virtual",
      "Advanced table management with TanStack Table",
      "Server-state management with TanStack Query",
      "State management with Zustand",
      "Multi-chain wallet integration",
      "Solana wallet connection with @solana/wallet-adapter-wallets",
      "EVM wallet integration with Reown AppKit",
      "Modern responsive trading dashboard UI",
    ],
    previewImages: [
      "/project-images/interra/full.png",
      "/project-images/interra/1.jpg",
      "/project-images/interra/2.jpg",
      "/project-images/interra/3.png",
    ],
    logo: "/project-images/interra/logo.svg",
  },
  {
    name: "HoofDAO",
    role: "Frontend Developer",
    summary:
      "A decentralized horse racing prediction platform featuring a modern web application and admin CMS for managing NFT assets, race prediction systems, financial operations, and user activities on the BNB Chain ecosystem.",
    responsibilities: [
      "Developed and maintained the main web application and admin CMS using ReactJS.",
      "Built responsive and visually polished dashboard interfaces for managing users, NFT assets, race predictions, and platform operations.",
      "Implemented multilingual support and translation systems for more than 10 countries.",
      "Integrated JWT-based authentication and role-based access control workflows.",
      "Developed backend APIs focused on item management, CMS operations, and administrative functionalities.",
      "Integrated blockchain-related frontend interactions using viem.",
      "Collaborated closely with backend and blockchain services to support decentralized platform workflows.",
    ],
    technicalHighlights: [
      "Modern admin dashboard and CMS architecture",
      "Responsive and polished UI/UX design",
      "Multi-language internationalization support",
      "Role-based access control system",
      "JWT authentication workflows",
      "BNB Chain integration",
      "Blockchain interaction with viem",
      "State management with Zustand",
      "Server-state handling with TanStack Query",
      "Modern component architecture with shadcn/ui",
      "RESTful API development with NestJS and Prisma",
    ],
    previewImages: [
      "/project-images/hoofdao/8.png",
      "/project-images/hoofdao/7.png",
      "/project-images/hoofdao/1.png",
      "/project-images/hoofdao/2.png",
      "/project-images/hoofdao/full.png",
      "/project-images/hoofdao/4.png",
      "/project-images/hoofdao/5.png",
      "/project-images/hoofdao/6.png",
    ],
    logo: "/project-images/hoofdao/logo.png",
  },
  {
    name: "Ponz",
    role: "Frontend Developer",
    summary:
      "A real-time Web3 social trading platform on Solana where users can create custom tokens, interact with communities, and trade assets with integrated reward mechanisms.",
    responsibilities: [
      "Developed and maintained the core frontend application using ReactJS.",
      "Built responsive and interactive UI experiences for token creation, trading, and community engagement.",
      "Integrated real-time features including chat systems, live updates, and token activity feeds using WebSocket.",
      "Implemented token-related backend features including profile management, token interactions, and social functionalities.",
      "Integrated TradingView charts for real-time market visualization.",
      "Collaborated on Web3 workflows and Solana-based transaction interactions.",
    ],
    technicalHighlights: [
      "Real-time communication with WebSocket",
      "Interactive trading dashboard",
      "Social features including chat and stickers",
      "Solana ecosystem integration",
      "Cloud asset storage with AWS S3",
    ],
    previewImages: [
      "/project-images/ponz/1.jpg",
      "/project-images/ponz/2.jpg",
      "/project-images/ponz/4.png",
      "/project-images/ponz/5.jpg",
      "/project-images/ponz/6.png",
      "/project-images/ponz/7.png",
      "/project-images/ponz/8.jpg",
    ],
    logo: "/project-images/ponz/logo.svg",
  },
  {
    name: "Node Farm",
    role: "Backend Developer",
    summary:
      "A decentralized reward platform integrated with Telegram Mini Apps, allowing users to purchase NFT-based assets, stake into reward pools, and earn TON-based daily rewards.",
    responsibilities: [
      "Designed and developed the entire backend architecture.",
      "Implemented Telegram Mini App authentication integrated with TON wallet verification.",
      "Built secure authentication and session handling systems.",
      "Developed TON blockchain transaction scanning and wallet monitoring services.",
      "Implemented staking pool systems and automated reward distribution logic.",
      "Handled item purchasing, extension, and reward management workflows.",
      "Optimized backend performance using Redis caching and real-time socket communication.",
      "Integrated Telegram Bot services for notifications and platform interactions.",
    ],
    technicalHighlights: [
      "TON blockchain integration",
      "Real-time transaction scanning",
      "Event-driven backend workflows",
      "Redis caching strategies",
      "Secure wallet authentication",
      "Telegram Mini App ecosystem",
    ],
    previewImages: [
      "/project-images/node-farm/4.jpg",
      "/project-images/node-farm/3.jpg",
      "/project-images/node-farm/2.jpg",
      "/project-images/node-farm/1.jpg",
    ],
  },
  {
    name: "DFantasy",
    role: "Backend Developer",
    summary:
      "A fantasy football platform inspired by Fantasy Premier League, supporting Web, Mobile, and Telegram Mini App experiences with real-time game synchronization.",
    responsibilities: [
      "Developed backend services and APIs for gameplay systems and user interactions.",
      "Implemented automated synchronization systems for Fantasy Premier League data using scheduled cron jobs.",
      "Built scalable backend logic for player statistics, team management, and ranking systems.",
      "Integrated Redis caching for performance optimization.",
      "Developed Telegram Mini App and bot-related backend integrations.",
    ],
    technicalHighlights: [
      "Cronjob-based data synchronization",
      "Realtime game data processing",
      "Redis performance optimization",
      "Telegram ecosystem integration",
      "Scalable backend APIs",
    ],
    previewImages: [
      "/project-images/dfantasy/2.jpg",
      "/project-images/dfantasy/1.jpg",
      "/project-images/dfantasy/3.jpg",
    ],
    logo: "/project-images/dfantasy/logo.svg",
  },
  {
    name: "Seagate",
    role: "Frontend Developer",
    summary:
      "A decentralized investment platform designed for launching Initial Package Offerings (IPO) for DePIN projects through Web3-powered investment workflows.",
    responsibilities: [
      "Developed and maintained the frontend application using NextJS.",
      "Built responsive UI components and investment dashboards.",
      "Implemented authentication flows, QR code utilities, and token-related user interfaces.",
      "Integrated state management and frontend business logic for investment workflows.",
      "Collaborated closely with backend services and blockchain-related integrations.",
    ],
    technicalHighlights: [
      "Modern responsive UI architecture",
      "Web3-oriented frontend workflows",
      "Authentication and security integrations",
      "State management with Zustand",
      "Optimized user experience with NextJS",
    ],
    previewImages: ["/project-images/seagate/1.jpg"],
    logo: "/project-images/seagate/logo.png",
  },
  {
    name: "EST Edu",
    role: "Full-stack Developer",
    summary:
      "An interactive e-learning platform that combines structured programming courses, real-time communication, video calls, and AI-powered career prediction systems.",
    responsibilities: [
      "Designed and developed both frontend and backend systems.",
      "Built course management, lesson management, and user authentication systems.",
      "Implemented real-time chat and communication features using Socket.io.",
      "Integrated WebRTC video calling for live learning sessions.",
      "Developed AI-powered career prediction functionality using machine learning services.",
      "Built dashboards, notifications, and interactive analytics systems.",
      "Designed MongoDB database structures and backend APIs.",
    ],
    technicalHighlights: [
      "Realtime communication systems",
      "WebRTC video integration",
      "AI-powered recommendation system",
      "Full-stack architecture",
      "Interactive analytics dashboard",
      "Scalable education platform",
    ],
    previewImages: [
      "/project-images/est-edu/full.png",
      "/project-images/est-edu/est-edu-1.jpg",
      "/project-images/est-edu/est-edu-2.jpg",
      "/project-images/est-edu/est-edu-8.png",
      "/project-images/est-edu/est-edu-3.jpg",
      "/project-images/est-edu/est-edu-4.jpg",
      "/project-images/est-edu/est-edu-5.jpg",
      "/project-images/est-edu/est-edu-6.jpg",
      "/project-images/est-edu/est-edu-7.jpg",
      "/project-images/est-edu/est-edu-9.png",
    ],
  },
  {
    name: "Van Thanh Clinic",
    role: "Backend Developer",
    summary:
      "A medical clinic platform including a public landing page and an internal CRM system for managing articles, banners, and medical content.",
    responsibilities: [
      "Designed and developed backend APIs for both landing page and admin CRM systems.",
      "Built content management features for articles, banners, and doctor information.",
      "Implemented authentication, validation, and CRUD management workflows.",
      "Designed MongoDB database schemas and integrated API documentation using Swagger.",
    ],
    technicalHighlights: [
      "RESTful API architecture",
      "Content management system (CMS)",
      "MongoDB database design",
      "Authentication and validation workflows",
      "Swagger API documentation",
    ],
    previewImages: [
      "/project-images/pk-bs-thanh-1.jpg",
      "/project-images/pk-bs-thanh-2.jpg",
      "/project-images/pk-bs-thanh-3.jpg",
      "/project-images/admin-pk-bs-thanh-1.jpg",
      "/project-images/admin-pk-bs-thanh-2.jpg",
    ],
  },
  {
    name: "Bwai Tech",
    role: "Full-stack Developer",
    summary:
      "A corporate website and admin management system for managing company products, careers, classes, and media content.",
    responsibilities: [
      "Developed frontend landing pages and backend management systems.",
      "Built admin dashboard features for managing products, careers, classes, and videos.",
      "Implemented CRUD operations, form validation, and content management workflows.",
      "Collaborated on responsive UI development and API integrations.",
    ],
    technicalHighlights: [
      "Admin dashboard system",
      "Responsive corporate website",
      "Content management workflows",
      "Form validation and API integration",
      "Full-stack web development",
    ],
    previewImages: [
      "/project-images/bwai-tech-1.png",
      "/project-images/bwai-tech-2.png",
      "/project-images/bwai-tech-admin-1.png",
      "/project-images/bwai-tech-admin-2.jpg",
      "/project-images/bwai-tech-admin-3.jpg",
    ],
  },
];

export const listExperience: IExperience[] = [
  {
    companyName: "Twendee",
    comanyLogo: "/experience/twendee.webp",
    positionWork: "Junior Full-stack JavaScript Developer",
    startTime: "June 2024",
    endTime: "Present",
    summary:
      "Working as a full-stack JavaScript developer building scalable web platforms, real-time systems, admin dashboards, and Web3 applications for international projects. Contributing across frontend and backend development, including modern UI implementation, API integration, blockchain-related features, realtime communication systems, performance optimization, and production-ready application architecture.",
  },
  {
    companyName: "BWAI TECH",
    comanyLogo: "/experience/bwai-tech.png",
    positionWork: "Web Developer",
    startTime: "February 2024",
    endTime: "April 2024",
    summary:
      "Worked as a full-stack web developer building both client and internal business systems, including landing pages, admin CMS platforms, and management dashboards. Participated in frontend architecture, backend API development, database design, and UI implementation while collaborating directly with real client projects in fast-paced development environments.",
  },
  {
    companyName: "Freelance",
    comanyLogo: "/experience/free.avif",
    positionWork: "Full-stack Developer",
    startTime: "September 2023",
    endTime: "January 2024",
    summary:
      "Worked as a freelance full-stack developer delivering landing pages, CMS platforms, and custom business systems for clients. Handled both frontend and backend development, including API integration, database design, authentication systems, and responsive UI implementation while working directly with client requirements and project deployment workflows.",
  },
  {
    companyName: "USOL VIETNAM",
    comanyLogo: "/experience/usol-v.jpg",
    positionWork: "Web Development Intern",
    startTime: "June 2023",
    endTime: "August 2023",
    summary:
      "Trained and worked within a professional Japanese software development workflow, contributing to real-world web application projects. Focused on frontend development with NextJS while collaborating closely with team members to build responsive and maintainable user interfaces. Also gained early leadership experience by coordinating and supporting a small development team during project implementation.",
  },
  {
    companyName: "Freelance",
    comanyLogo: "/experience/free.avif",
    positionWork: "Frontend Developer",
    startTime: "2022",
    endTime: "June 2023",
    summary:
      "Started working as a freelance frontend developer, building responsive websites and user interfaces for small business and personal projects. Gained hands-on experience in modern frontend development, UI implementation, client communication, and translating design concepts into functional web applications.",
  },
];
